import { useState } from "react";
import axios from "axios";
import { toast } from "sonner";
import { X, Wand2 } from "lucide-react";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const PLATFORMS = ["instagram", "facebook", "linkedin", "twitter", "threads", "youtube"];

export default function GeneratePostModal({ open, onClose, clients, onGenerated }) {
  const [form, setForm] = useState({ client_id: "", platform: "instagram", topic: "", scheduled_at: "" });
  const [generating, setGenerating] = useState(false);

  const generate = async (e) => {
    e.preventDefault();
    if (!form.client_id) return toast.error("Select a client");
    setGenerating(true);
    try {
      const resp = await axios.post(`${API}/posts/generate`, {
        client_id: form.client_id,
        platform: form.platform,
        content_type: "text_post",
        topic: form.topic || undefined,
        scheduled_at: form.scheduled_at || undefined,
      });
      toast.success("Post generated by AI");
      onGenerated(resp.data);
      onClose();
      setForm({ client_id: "", platform: "instagram", topic: "", scheduled_at: "" });
    } catch (e) {
      toast.error(e.response?.data?.detail || "AI generation failed");
    } finally {
      setGenerating(false);
    }
  };

  if (!open) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70">
      <div className="bg-zinc-900 border border-zinc-700 w-full max-w-md p-0">
        <div className="flex items-center justify-between px-5 py-4 border-b border-zinc-800">
          <div className="text-sm font-bold text-white">Generate with AI</div>
          <button onClick={onClose} className="text-zinc-500 hover:text-white transition-colors duration-150"><X size={16} /></button>
        </div>
        <form onSubmit={generate} className="p-5 space-y-4">
          <div>
            <label className="block text-[10px] font-mono text-zinc-500 uppercase mb-1.5">Client *</label>
            <select
              value={form.client_id}
              onChange={e => setForm(f => ({ ...f, client_id: e.target.value }))}
              className="w-full bg-zinc-950 border border-zinc-700 px-3 py-2 text-sm text-white focus:outline-none focus:border-zinc-500"
            >
              <option value="">Select client...</option>
              {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-[10px] font-mono text-zinc-500 uppercase mb-1.5">Platform</label>
            <select
              value={form.platform}
              onChange={e => setForm(f => ({ ...f, platform: e.target.value }))}
              className="w-full bg-zinc-950 border border-zinc-700 px-3 py-2 text-sm text-white focus:outline-none focus:border-zinc-500"
            >
              {PLATFORMS.map(p => <option key={p} value={p}>{p.charAt(0).toUpperCase() + p.slice(1)}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-[10px] font-mono text-zinc-500 uppercase mb-1.5">Topic (optional)</label>
            <input
              value={form.topic}
              onChange={e => setForm(f => ({ ...f, topic: e.target.value }))}
              placeholder="e.g. product launch, tips for..."
              className="w-full bg-zinc-950 border border-zinc-700 px-3 py-2 text-sm text-white placeholder-zinc-600 focus:outline-none focus:border-zinc-500"
            />
          </div>
          <div>
            <label className="block text-[10px] font-mono text-zinc-500 uppercase mb-1.5">Schedule At (optional)</label>
            <input
              type="datetime-local"
              value={form.scheduled_at}
              onChange={e => setForm(f => ({ ...f, scheduled_at: e.target.value ? new Date(e.target.value).toISOString() : "" }))}
              className="w-full bg-zinc-950 border border-zinc-700 px-3 py-2 text-sm text-white focus:outline-none focus:border-zinc-500 [color-scheme:dark]"
            />
          </div>
          <div className="flex gap-3 pt-1">
            <button type="button" onClick={onClose} className="flex-1 py-2 text-sm border border-zinc-700 text-zinc-400 hover:bg-zinc-800 transition-colors duration-150">
              Cancel
            </button>
            <button
              type="submit"
              disabled={generating}
              className="flex-1 py-2 text-sm bg-white text-black font-semibold hover:bg-zinc-200 transition-colors duration-150 disabled:opacity-50 flex items-center justify-center gap-2"
            >
              <Wand2 size={13} className={generating ? "animate-spin" : ""} />
              {generating ? "Generating..." : "Generate"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
