import { useState, useEffect, useCallback, useRef } from "react";
import axios from "axios";
import { toast } from "sonner";
import { Send, Trash2, CheckCircle, Wand2, Filter, RefreshCw, Clock, X, BadgeCheck } from "lucide-react";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

const STATUSES = ["all", "draft", "scheduled", "published", "failed"];
const PLATFORMS = ["instagram", "facebook", "linkedin", "twitter", "threads", "youtube"];

const STATUS_BADGE = {
  draft: "border-zinc-700 text-zinc-400",
  scheduled: "border-amber-700 text-amber-400",
  published: "border-emerald-700 text-emerald-400",
  failed: "border-red-900 text-red-400",
  publishing: "border-blue-700 text-blue-400",
};

function GenerateModal({ open, onClose, clients, onGenerated }) {
  const [form, setForm] = useState({ client_id: "", platform: "instagram", topic: "", scheduled_at: "" });
  const [generating, setGenerating] = useState(false);

  const generate = async (e) => {
    e.preventDefault();
    if (!form.client_id) return toast.error("Select a client");
    setGenerating(true);
    try {
      const resp = await axios.post(`${API}/posts/generate`, {
        client_id: form.client_id,
        platform: form.platform,
        content_type: "text_post",
        topic: form.topic || undefined,
        scheduled_at: form.scheduled_at || undefined,
      });
      toast.success("Post generated by AI");
      onGenerated(resp.data);
      onClose();
      setForm({ client_id: "", platform: "instagram", topic: "", scheduled_at: "" });
    } catch (e) {
      toast.error(e.response?.data?.detail || "AI generation failed");
    } finally {
      setGenerating(false);
    }
  };

  if (!open) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70">
      <div className="bg-zinc-900 border border-zinc-700 w-full max-w-md p-0">
        <div className="flex items-center justify-between px-5 py-4 border-b border-zinc-800">
          <div className="text-sm font-bold text-white">Generate with AI</div>
          <button onClick={onClose} className="text-zinc-500 hover:text-white transition-colors duration-150"><X size={16} /></button>
        </div>
        <form onSubmit={generate} className="p-5 space-y-4">
          <div>
            <label className="block text-[10px] font-mono text-zinc-500 uppercase mb-1.5">Client *</label>
            <select
              data-testid="gen-client-select"
              value={form.client_id}
              onChange={e => setForm(f => ({ ...f, client_id: e.target.value }))}
              className="w-full bg-zinc-950 border border-zinc-700 px-3 py-2 text-sm text-white focus:outline-none focus:border-zinc-500"
            >
              <option value="">Select client...</option>
              {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-[10px] font-mono text-zinc-500 uppercase mb-1.5">Platform</label>
            <select
              data-testid="gen-platform-select"
              value={form.platform}
              onChange={e => setForm(f => ({ ...f, platform: e.target.value }))}
              className="w-full bg-zinc-950 border border-zinc-700 px-3 py-2 text-sm text-white focus:outline-none focus:border-zinc-500"
            >
              {PLATFORMS.map(p => <option key={p} value={p}>{p.charAt(0).toUpperCase() + p.slice(1)}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-[10px] font-mono text-zinc-500 uppercase mb-1.5">Topic (optional)</label>
            <input
              data-testid="gen-topic-input"
              value={form.topic}
              onChange={e => setForm(f => ({ ...f, topic: e.target.value }))}
              placeholder="e.g. product launch, tips for..."
              className="w-full bg-zinc-950 border border-zinc-700 px-3 py-2 text-sm text-white placeholder-zinc-600 focus:outline-none focus:border-zinc-500"
            />
          </div>
          <div>
            <label className="block text-[10px] font-mono text-zinc-500 uppercase mb-1.5">Schedule At (optional)</label>
            <input
              data-testid="gen-schedule-input"
              type="datetime-local"
              value={form.scheduled_at}
              onChange={e => setForm(f => ({ ...f, scheduled_at: e.target.value ? new Date(e.target.value).toISOString() : "" }))}
              className="w-full bg-zinc-950 border border-zinc-700 px-3 py-2 text-sm text-white focus:outline-none focus:border-zinc-500 [color-scheme:dark]"
            />
          </div>
          <div className="flex gap-3 pt-1">
            <button type="button" onClick={onClose} className="flex-1 py-2 text-sm border border-zinc-700 text-zinc-400 hover:bg-zinc-800 transition-colors duration-150">
              Cancel
            </button>
            <button
              type="submit"
              data-testid="generate-post-btn"
              disabled={generating}
              className="flex-1 py-2 text-sm bg-white text-black font-semibold hover:bg-zinc-200 transition-colors duration-150 disabled:opacity-50 flex items-center justify-center gap-2"
            >
              <Wand2 size={13} className={generating ? "animate-spin" : ""} />
              {generating ? "Generating..." : "Generate"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

export default function ContentQueue() {
  const [posts, setPosts] = useState([]);
  const [clients, setClients] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeStatus, setActiveStatus] = useState("all");
  const [filterClient, setFilterClient] = useState("");
  const [filterPlatform, setFilterPlatform] = useState("");
  const [filterContentType, setFilterContentType] = useState("");
  const [showGenerate, setShowGenerate] = useState(false);
  const [publishing, setPublishing] = useState({});
  const publishingInFlight = useRef(new Set());

  const fetchData = useCallback(async () => {
    try {
      const [postsResp, clientsResp] = await Promise.all([
        axios.get(`${API}/posts`, { params: { status: activeStatus === "all" ? undefined : activeStatus, limit: 200 } }),
        axios.get(`${API}/clients`)
      ]);
      setPosts(postsResp.data);
      setClients(clientsResp.data);
    } catch { toast.error("Failed to load posts"); }
    finally { setLoading(false); }
  }, [activeStatus]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const filtered = posts.filter(p => {
    if (filterClient && p.client_id !== filterClient) return false;
    if (filterPlatform && p.platform !== filterPlatform) return false;
    if (filterContentType && p.content_type !== filterContentType) return false;
    return true;
  });

  const publishNow = async (post) => {
    if (publishingInFlight.current.has(post.id)) return;
    publishingInFlight.current.add(post.id);
    setPublishing(prev => ({ ...prev, [post.id]: true }));
    // Instagram without image triggers auto-render (~10s) — warn user
    const needsRender = post.platform === "instagram" && !post.image_url;
    if (needsRender) toast.info("Rendering post as image for Instagram... (~10s)", { duration: 12000 });
    try {
      const resp = await axios.post(`${API}/posts/${post.id}/publish`, {}, { timeout: 60000 });

      if (resp.data.status === "retrying_local") {
        toast.info("Retrying with local storage...", { duration: 20000 });
        try {
          const resp2 = await axios.post(
            `${API}/posts/${post.id}/publish?local_fallback=true`, {}, { timeout: 120000 }
          );
          setPosts(prev => prev.map(p => p.id === post.id ? { ...p, ...resp2.data } : p));
          if (resp2.data.status === "published") {
            toast.success("Post published to Instagram!");
          } else if (resp2.data.status === "retrying_local") {
            toast.error("Publishing service unavailable. Please try again later.");
          } else {
            toast.error(`Publish failed: ${resp2.data.error_message || "Unknown error"}`);
          }
        } catch (e2) {
          toast.error(e2.response?.data?.detail || "Local fallback publish failed");
        }
        return;
      }

      setPosts(prev => prev.map(p => p.id === post.id ? { ...p, ...resp.data } : p));
      if (resp.data.status === "published") {
        toast.success("Post published to Instagram!");
      } else {
        toast.error(`Publish failed: ${resp.data.error_message || "Unknown error"}`);
      }
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to publish");
    } finally {
      publishingInFlight.current.delete(post.id);
      setPublishing(prev => ({ ...prev, [post.id]: false }));
    }
  };

  const approvePost = async (post) => {
    try {
      await axios.post(`${API}/posts/${post.id}/approve`);
      setPosts(prev => prev.map(p => p.id === post.id ? { ...p, status: "scheduled" } : p));
      toast.success("Post approved and scheduled");
    } catch { toast.error("Failed to approve"); }
  };

  const deletePost = async (postId) => {
    try {
      await axios.delete(`${API}/posts/${postId}`);
      setPosts(prev => prev.filter(p => p.id !== postId));
      toast.success("Post deleted");
    } catch { toast.error("Failed to delete"); }
  };

  const markPublished = async (postId) => {
    try {
      const resp = await axios.post(`${API}/posts/${postId}/mark-published`);
      setPosts(prev => prev.map(p => p.id === postId ? { ...p, ...resp.data } : p));
      toast.success("Post marked as published");
    } catch { toast.error("Failed to mark as published"); }
  };

  const counts = {
    all: posts.length,
    draft: posts.filter(p => p.status === "draft").length,
    scheduled: posts.filter(p => p.status === "scheduled").length,
    published: posts.filter(p => p.status === "published").length,
    failed: posts.filter(p => p.status === "failed").length,
  };

  return (
    <div className="p-6" data-testid="content-queue-page">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl font-bold text-white">Content Queue</h1>
          <p className="text-xs text-zinc-500 font-mono mt-0.5">{filtered.length} posts matching filters</p>
        </div>
        <div className="flex gap-2">
          <button onClick={fetchData} className="p-2 border border-zinc-800 text-zinc-500 hover:text-white hover:bg-zinc-800 transition-colors duration-150">
            <RefreshCw size={14} />
          </button>
          <button
            onClick={() => setShowGenerate(true)}
            data-testid="open-generate-modal-btn"
            className="flex items-center gap-2 px-4 py-2 bg-white text-black text-sm font-semibold hover:bg-zinc-200 transition-colors duration-150"
          >
            <Wand2 size={14} />
            AI Generate
          </button>
        </div>
      </div>

      {/* Status Tabs */}
      <div className="flex items-center gap-0 border border-zinc-800 mb-4 w-fit">
        {STATUSES.map(s => (
          <button
            key={s}
            data-testid={`tab-${s}`}
            onClick={() => setActiveStatus(s)}
            className={`px-4 py-2 text-xs font-mono uppercase transition-colors duration-150 border-r border-zinc-800 last:border-0 ${
              activeStatus === s ? "bg-white text-black font-semibold" : "text-zinc-500 hover:text-white hover:bg-zinc-800"
            }`}
          >
            {s} <span className="ml-1 opacity-60">{counts[s]}</span>
          </button>
        ))}
      </div>

      {/* Filters */}
      <div className="flex gap-3 mb-4">
        <div className="flex items-center gap-2 bg-zinc-900 border border-zinc-800 px-3 py-1.5">
          <Filter size={11} className="text-zinc-600" />
          <select
            data-testid="filter-client-select"
            value={filterClient}
            onChange={e => setFilterClient(e.target.value)}
            className="bg-transparent text-xs font-mono text-zinc-400 focus:outline-none"
          >
            <option value="">All Clients</option>
            {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
          </select>
        </div>
        <div className="flex items-center gap-2 bg-zinc-900 border border-zinc-800 px-3 py-1.5">
          <Filter size={11} className="text-zinc-600" />
          <select
            data-testid="filter-platform-select"
            value={filterPlatform}
            onChange={e => setFilterPlatform(e.target.value)}
            className="bg-transparent text-xs font-mono text-zinc-400 focus:outline-none"
          >
            <option value="">All Platforms</option>
            {PLATFORMS.map(p => <option key={p} value={p}>{p}</option>)}
          </select>
        </div>
        {(filterClient || filterPlatform || filterContentType) && (
          <button
            onClick={() => { setFilterClient(""); setFilterPlatform(""); setFilterContentType(""); }}
            className="text-xs font-mono text-zinc-500 hover:text-white transition-colors duration-150"
          >
            Clear filters
          </button>
        )}
      </div>

      {/* Content type filter */}
      <div className="flex gap-2 mb-4">
        {[["", "All Types"], ["text_post", "Text"], ["carousel", "Carousel"], ["video", "Video"]].map(([val, label]) => (
          <button
            key={val}
            onClick={() => setFilterContentType(val)}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium ${filterContentType === val ? "bg-violet-600 text-white" : "bg-white/5 text-neutral-400 hover:text-white"}`}
          >
            {label}
          </button>
        ))}
      </div>

      {/* Posts Table */}
      <div className="bg-zinc-900 border border-zinc-800">
        <div className="grid grid-cols-12 gap-2 px-4 py-2 border-b border-zinc-800 text-[10px] font-mono text-zinc-500 uppercase tracking-widest">
          <div className="col-span-4">Content</div>
          <div className="col-span-2">Client</div>
          <div className="col-span-1">Platform</div>
          <div className="col-span-2">Scheduled</div>
          <div className="col-span-1 text-center">Status</div>
          <div className="col-span-2 text-right">Actions</div>
        </div>

        {loading ? (
          <div className="px-4 py-8 text-center text-zinc-600 font-mono text-sm">Loading posts...</div>
        ) : filtered.length === 0 ? (
          <div className="px-4 py-12 text-center text-zinc-600 font-mono text-sm">
            No posts found. Generate some content with AI.
          </div>
        ) : (
          filtered.map(post => (
            <div key={post.id} className="grid grid-cols-12 gap-2 px-4 py-3 data-row" data-testid={`post-row-${post.id}`}>
              <div className="col-span-4">
                <p className="text-xs text-zinc-300 font-mono line-clamp-2 leading-relaxed">{post.text}</p>
                {post.ai_generated && (
                  <span className="text-[9px] font-mono text-zinc-600 mt-0.5 block">AI GENERATED</span>
                )}
                {post.status === "failed" && post.error_message && (
                  <span className="text-[9px] font-mono text-red-500 mt-0.5 block line-clamp-1" title={post.error_message}>
                    {post.error_message}
                  </span>
                )}
                {post.content_type === "video" && post.job_priority && (
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${
                    post.job_priority === "high" ? "bg-red-500/20 text-red-400" :
                    post.job_priority === "low" ? "bg-neutral-700 text-neutral-400" :
                    "bg-yellow-500/20 text-yellow-400"
                  }`}>
                    {post.job_priority === "high" ? "🔴" : post.job_priority === "low" ? "⚪" : "🟡"} {post.job_priority}
                  </span>
                )}
                {post.content_type === "video" && post.video_url && (
                  <span className="text-xs px-2 py-0.5 rounded-full bg-violet-500/20 text-violet-400">🎬 video</span>
                )}
              </div>
              <div className="col-span-2 flex items-center">
                <span className="text-xs text-zinc-400 font-mono truncate">{post.client_name}</span>
              </div>
              <div className="col-span-1 flex items-center">
                <span className="text-[10px] font-mono text-zinc-500 uppercase">{post.platform?.slice(0,3)}</span>
              </div>
              <div className="col-span-2 flex items-center">
                <div>
                  <Clock size={10} className="text-zinc-600 inline mr-1" />
                  <span className="text-[10px] font-mono text-zinc-500">
                    {post.scheduled_at ? new Date(post.scheduled_at).toLocaleString("en-US", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "—"}
                  </span>
                </div>
              </div>
              <div className="col-span-1 flex items-center justify-center">
                <span className={`text-[9px] font-mono px-1.5 py-0.5 border ${STATUS_BADGE[post.status] || "border-zinc-700 text-zinc-500"}`}>
                  {post.status?.toUpperCase()}
                </span>
              </div>
              <div className="col-span-2 flex items-center justify-end gap-1">
                {post.status === "draft" && (
                  <button
                    data-testid={`approve-btn-${post.id}`}
                    onClick={() => approvePost(post)}
                    title="Approve"
                    className="p-1.5 text-zinc-500 hover:text-emerald-400 border border-transparent hover:border-emerald-900 transition-colors duration-150"
                  >
                    <CheckCircle size={13} />
                  </button>
                )}
                {(post.status === "draft" || post.status === "scheduled" || post.status === "failed") && (
                  <button
                    data-testid={`publish-btn-${post.id}`}
                    onClick={() => publishNow(post)}
                    disabled={publishing[post.id]}
                    title="Publish Now"
                    className="p-1.5 text-zinc-500 hover:text-blue-400 border border-transparent hover:border-blue-900 transition-colors duration-150 disabled:opacity-30"
                  >
                    <Send size={13} className={publishing[post.id] ? "animate-pulse" : ""} />
                  </button>
                )}
                {post.status === "failed" && post.error_message?.includes("temporarily restricted") && (
                  <button
                    data-testid={`mark-published-btn-${post.id}`}
                    onClick={() => markPublished(post.id)}
                    title="Mark as Published"
                    className="p-1.5 text-zinc-500 hover:text-emerald-400 border border-transparent hover:border-emerald-900 transition-colors duration-150"
                  >
                    <BadgeCheck size={13} />
                  </button>
                )}
                <button
                  data-testid={`delete-post-btn-${post.id}`}
                  onClick={() => deletePost(post.id)}
                  title="Delete"
                  className="p-1.5 text-zinc-500 hover:text-red-400 border border-transparent hover:border-red-900 transition-colors duration-150"
                >
                  <Trash2 size={13} />
                </button>
              </div>
            </div>
          ))
        )}
      </div>

      <GenerateModal
        open={showGenerate}
        onClose={() => setShowGenerate(false)}
        clients={clients}
        onGenerated={(post) => { setPosts(prev => [post, ...prev]); }}
      />
    </div>
  );
}
